version: "3.9"
services:
  postgresql:
    container_name: "db-api"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "apirest"
    ports:
      - "15432:5432"
  node:
    container_name: "nodejs"
    image: "node:17"
    user: "node"
    restart: unless-stopped
    env_file: .env
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "3001:3001"
    command: "npm run dev"
    depends_on:
      - postgresql
